Finished Market and Inventory classes
RobinStephenson/jbt pull request #16
Opened 2016-11-26 23:12 UTC by Mikeywalsh

Finished Market and Inventory classes, as well as all documentation and extensive test classes for use with the built in unity editor test runner.

2016-11-28 12:45 UTC, RobinStephenson approved these changes

2016-11-28 12:50 UTC, RobinStephenson requested changes

2016-11-28 12:50 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Classes/Inventory.cs
> +sealed public class Inventory
Is it worth adding owned tiles to the inventory so that later on its easy for players to trade tiles?

2016-11-28 12:51 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/InventoryTest.cs
> +        bool successful = inv1.TransferMoney(2, inv2);
shouldnt this throw an error rather than return false?

2016-11-28 12:53 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/InventoryTest.cs
> +        bool successful = inv1.TransferMoney(2, inv2);
I think it would make sense for this to return itself rather than bool so you can chain methods

2016-11-28 12:53 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/InventoryTest.cs
> +        bool successful = inv1.TransferMoney(2, inv2);
same goes for items

2016-11-28 13:01 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/MarketTest.cs
> +    public void GettingBuyPrices()
maybe move the prices into the constructor so we can set them in the tests and check theyre the same here

2016-11-28 13:01 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/MarketTest.cs
> +    public void GettingSellPrices()
same as above

2016-11-28 13:02 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/MarketTest.cs
> +    public void FailedBuy()
again i think we should throw an error rather than return false

2016-11-28 14:13 UTC, Mikeywalsh commented on RoboticonColony/Assets/Code/Classes/Inventory.cs
> +sealed public class Inventory
Can't see why not, will have to wait for Tom to get finished with his Tile class though. The inventory could just be the place where player owned tiles are stored anyway couldn't it?

2016-11-29 02:57 UTC, Mikeywalsh commented on RoboticonColony/Assets/Editor/Unit_Tests/MarketTest.cs
> +    public void FailedBuy()
Done

2016-11-29 02:57 UTC, Mikeywalsh commented on RoboticonColony/Assets/Editor/Unit_Tests/MarketTest.cs
> +    public void GettingSellPrices()
Done

2016-11-29 02:57 UTC, Mikeywalsh commented on RoboticonColony/Assets/Editor/Unit_Tests/MarketTest.cs
> +    public void GettingBuyPrices()
Done

2016-11-29 02:59 UTC, Mikeywalsh commented
I've also created a TestHelper class, which has its own Throws method that works identically to NUnits Throws method. I did this to save time on testing exceptions being thrown, as without NUnits Throws method, it takes almost the same 9 lines of code each time to test if a given exception is thrown. Now it can be done in one. I've also done tests for this new class. Let me know if it is too complex or will cause an issue!

2016-11-29 09:46 UTC, RobinStephenson approved these changes

2016-11-29 09:51 UTC, RobinStephenson commented
If all those tests are passing that looks good to me. one thing to note in future its best practice to keep your commits small and cohesive. so instead of 	"Made required changes and also implemented a TestHelper class with a …" you should do two commits, one for the changes, and one for the test helper, its also worth rather than saying required changes, saying what the changes were, so people not looking at this pull request can quickly see what the commit was. Other than that good work!

2016-11-30 10:49 UTC, merged