Tile
RobinStephenson/jbt pull request #26
Opened 2017-01-13 18:09 UTC by tc975

Tile and TileTest complete except for the parts that require Player and Roboticon

2017-01-13 18:44 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/PhysicalTile.cs
> +public class PhysalTile : MonoBehaviour {
Is this a typo?

2017-01-13 18:45 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    public int OwnerID { get; private set; }
Perhaps rather than an ownerId we should have a reference to the owners object

2017-01-13 18:49 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +        OwnerID = -1;
if we change this to be a reference to the owner rather than an id we should make this null

2017-01-13 18:51 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    //    _Resources[ItemType.Roboticon] = newRoboticon;
maybe roboticons should be kept separately from resources as they arent the same catergory

2017-01-13 18:52 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    /// Adds the resources on the tile to the player's inventory
I think this method should just return a production value for the resources as adding the resources to the player inventory isnt really the concern of a tile

2017-01-14 11:41 UTC, RobinStephenson commented on RoboticonColony/Assets/Editor/Unit_Tests/TileTest.cs
> +public class TileTest
We should implement these tests before merging . We should also have some tests for when things go wrong, ie assert errors when someone tries to use AddRoboticon invalidly and so on

2017-01-14 11:43 UTC, RobinStephenson requested changes
Still needs things like rendering in the scene. Probably should merge the class into the mono behaviour as well.
Definitely a good start though and most problems are easy fixes

2017-01-14 15:47 UTC, Mikeywalsh commented
Rendering is done automatically through unity, if we make tile a monobehavior then we will have to rewrite some of it, as monobehaviors do not behave like classes:

1) Monibehaviors need a corresponding game object in the scene to exist, the game object handles rendering and has other components such as transform
2) Monobehaviors exist when the game starts or if they are created at runtime, they do not have constructors, and instead use the Start() method which handles all their creation logic

If you do combine both tile classes into one, then I guess you could handle creating the roboticon Sprite over a tile if it has one on it. If roboticons have more than one Sprite for different customisations then Matthew would need to include a path to the Sprite as a member of roboticon. All sprites we load at runtime go in a folder we call 'Resources' in the unity project root. I know it's a lot to take in, if you want I can take over and do the unity specific stuff

2017-01-14 16:04 UTC, RobinStephenson commented
Sorry I should have been clearer what i meant by rendering. I mean we need methods to change the appearance of the tile, for example to set it as the tile currently selected by the user, then the tile class should update its sprite to one with a highlight or something. And it should automatically change sprites for installed roboticons etc when one is installed or removed.
As for keeping it separate from the monobehaviour that's fine with me if you think its better this way.

2017-01-14 16:20 UTC, RobinStephenson commented
Also did you mean to merge into Tile-Player-Robo rather than master?

2017-01-14 16:33 UTC, Mikeywalsh commented
That would be my fault since I told him to. I thought it would be better to have you three put your classes into another branch and finish them off fully before finally pushing to master since master should always be a working version of the project.
But i've ever really done a proper group git project before so im unsure if this is actually ever done or not, sorry if it isn't!

2017-01-14 16:35 UTC, RobinStephenson commented
No that's a good idea! I was just checking. I think we just need the tests to be finished and the other changes I mentioned unless anyone disagrees

2017-01-14 17:07 UTC, Mart500 commented
Would it not be easier to just add sprites like an overlay rather than
change the tile sprite. Whichever is easier.

On 14 January 2017 at 16:04, Robin Stephenson <notifications@github.com>
wrote:

> Sorry I should have been clearer what i meant by rendering. I mean we need
> methods to change the appearance of the tile, for example to set it as the
> tile currently selected by the user, then the tile class should update its
> sprite to one with a highlight or something. And it should automatically
> change sprites for installed roboticons etc when one is installed or
> removed.
> As for keeping it separate from the monobehaviour that's fine with me if
> you think its better this way.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RobinStephenson/jbt/pull/26#issuecomment-272633168>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMPQ-Y9tb82znt4QB6kTqfZbTYySv6Spks5rSPH_gaJpZM4LjJem>
> .
>

2017-01-14 17:14 UTC, RobinStephenson commented
Yeah just rendering a highlight on top of the tile makes more sense but we still need the methods to do it.

2017-01-14 18:07 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +    private int _ownerID;
If owner ID is changed to a reference this needs to change also too.

private (ownerclass) _selectedOwner = new (ownerclass) 

Something like this?

2017-01-14 18:07 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +    public int Ore
Better to merge these?

public int GetResource(ItemType resourceType){
         return _Resources[resourceType];
}

2017-01-14 19:27 UTC, Mikeywalsh requested changes
You're not using ItemType like it should be, you'll need references to an actual Roboticon object in the class.

2017-01-14 19:27 UTC, Mikeywalsh commented on RoboticonColony/Assets/Code/Tile.cs
> +    //    _Resources[ItemType.Roboticon] = newRoboticon;
This wouldn't even compile anyway. Read my other comment. _Resources is an itemtype>int dictionary, you can't, and shouldn't try to assign roboticon to it, as it makes no sense. ItemType.Roboticon is only ever used for keeping track of how many roboticons the player or market has in their inventory before they actually deploy it onto a tile.

2017-01-14 19:29 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    private int _ownerID;
You wouldnt want a new instance of the owner, just pass in a reference to a player class

2017-01-14 19:30 UTC, Mikeywalsh commented on RoboticonColony/Assets/Code/Tile.cs
> +    //    _Resources[ItemType.Roboticon] = null;
Same here. You should be setting a reference of roboticon to be null.

2017-01-14 19:31 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    public int Ore
I think both are valid. Might be useful to have both, your suggestion to allow enumeration, and the existing implementation for readability

2017-01-15 16:03 UTC, RobinStephenson requested changes
Hard to do the review with code commented out as its hard to see whats code and whats not. remove it and ill have another look.
As well there are some other changes that need doing such as still having ownerid rather than owner and python style private vars

2017-01-15 16:03 UTC, RobinStephenson commented on RoboticonColony/ProjectSettings/ProjectVersion.txt
> +m_EditorVersion: 5.4.3f1
You need to update your version of Unity if youre on your own PC

2017-01-15 16:03 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    //public Player OwnerID { get; private set; }
Shouldnt comment out code. just remove it

2017-01-15 16:03 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
>      private Dictionary<ItemType, int> _Resources;
Still using python style _Name for private stuff

2017-01-15 16:03 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> -    public int OwnerID { get; private set; }
OwnerID should be changed into Owner of type AbstractPlayer

2017-01-15 16:31 UTC, RobinStephenson requested changes

2017-01-15 16:31 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    public Roboticon InstalledRoboticon
You dont need to have both a public and a private installed roboticon

2017-01-15 16:31 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    public int ProduceOre()
ProduceOre and ProducePower are just the same as the respective properties

2017-01-15 16:31 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    public void AddPlayer(Player player)
Player has a private set but this method which lets you set without any checks. Better to just make player public or remove this method

2017-01-15 16:31 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    private Roboticon installedRoboticon { get; set; }
Dont see why private member has a get and set?

2017-01-15 16:31 UTC, RobinStephenson commented on RoboticonColony/Assets/Code/Tile.cs
> +    public void AddRoboticon(Roboticon newRoboticon)
For add and remove roboticon see comment above about installedRoboticon being private/public as im not sure what its meant to be at the moment

2017-01-15 18:27 UTC, Mart500 reviewed
Just some small stuff

2017-01-15 18:27 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +    public void AddRoboticon(Roboticon newRoboticon)
If you set it public then this function becomes redundant

2017-01-15 20:09 UTC, RobinStephenson approved these changes

2017-01-15 20:10 UTC, RobinStephenson commented
@Mikeywalsh What do you think of the new changes? I think anything else we can iron out when we merge the other classes in

2017-01-16 09:51 UTC, Mart500 requested changes
Issues with redundant functions. If not fixed before merge, wrong addressing of the class could be used else where.

2017-01-16 09:51 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +    public void AddRoboticon(Roboticon newRoboticon)
Now that installedRoboticon is public this is redundant

2017-01-16 09:51 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +        //Will apply roboticon multiplier later on
Calculation of production is already handled within the Roboticon class. Function should be removed.

2017-01-16 09:51 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +    public void AddPlayer(Player player)
Now Owner is public and so is the setter, This is redundant and should be removed.

2017-01-16 09:51 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +        //Will apply roboticon multiplier later on
Calculation of production is already handled within the Roboticon class. Function should be removed.

2017-01-16 09:51 UTC, Mart500 commented on RoboticonColony/Assets/Code/Tile.cs
> +    public int Ore
Combine these 2 into a function

public int GetResources(ItemType resourceType) {
     return resources[resourceType];
}

2017-01-16 10:47 UTC, Mikeywalsh commented on RoboticonColony/Assets/Code/Tile.cs
> +        //Will apply roboticon multiplier later on
I think we need @RobinStephenson to clear this up a bit. In the UML diagram from assessment one, both Roboticon and Tile have a Produce method in them!

2017-01-16 14:03 UTC, Mikeywalsh approved these changes

2017-01-16 14:06 UTC, Mikeywalsh requested changes
Looks good! I think we just need @RobinStephenson to clear up the Produce Method. In the UML diagram it is used in both Tile and Roboticon, but surely it should only be in one class. At the moment, both @Mart500 and @tc975 have their own implementations of it.

2017-01-19 15:33 UTC, Mikeywalsh approved these changes

2017-01-19 15:38 UTC, Mikeywalsh commented
Looks good, just waiting on @Mart500 to approve now!

2017-01-19 17:01 UTC, Mart500 commented
@Mikeywalsh @RobinStephenson @tc975 I just finished cleaning the class up a little. I think it should be ready for merging now.

2017-01-19 17:07 UTC, RobinStephenson commented
@Mart500 you need to set yourself as approving the changes for anyone to be able to merge

2017-01-19 17:10 UTC, Mart500 approved these changes

2017-01-19 17:24 UTC, Mart500 commented
@RobinStephenson Fixed

2017-01-19 17:29 UTC, RobinStephenson commented
okay someone just needs to resolve the merge conflicts first

2017-01-19 22:21 UTC, merged